#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Diff our Cluster Placement Summary against upstream's, term by term.

🔑 **The per-term oracle.** The clustering and shaping gates stop before the annealer; this is the
first one that scores the placement cost itself, and it scores each of the nine terms separately.
A single total cancels a win in one term against a loss in another.

⛔ **The reference tables come from `hmplogs/`**, generated by `run_hmp.sh` at `set_debug_level MPL
hierarchical_macro_placement 2`. They are NOT in the `.ok` goldens: the summary only prints under
that debug level, and no case sets it.

⚠️ **`set_macro_guidance_region` is a COMMAND, not database state** — the same trap as the halo
commands. A prepared `.odb` cannot carry it, so it is re-read from the case `.tcl` here. Anything
in a `.tcl` that is not in KNOWN is being silently ignored.

ℹ️ A design whose root is a macro cluster prints a *Macro* Placement Summary instead and is
reported as `macro-path`, not as a failure — that is a different stage.

Usage:  python3 scripts/compare-placement.py <odb-dir> [hmplog-dir] [tcl-dir]
"""
import io, os, re, subprocess, sys

odb_dir = sys.argv[1] if len(sys.argv) > 1 else "/tmp/mplodb"
log_dir = sys.argv[2] if len(sys.argv) > 2 else os.path.join(odb_dir, "hmplogs")
tcl_dir = sys.argv[3] if len(sys.argv) > 3 else odb_dir

MACRO_HALO = re.compile(r"set_macro_halo\s+-macro_name\s+(\S+)\s+-halo\s*\{([^}]*)\}")
BASE_HALO = re.compile(r"set_macro_base_halo\s+([0-9.\s]+)")
GUIDE = re.compile(r"set_macro_guidance_region\s+-macro_name\s+(\S+)\s+-region\s*\{([^}]*)\}")
# ⛔ `rtl_macro_placer`'s own threshold options are engine state too. Supplying them keeps the
# tree's `max_level` at 2, and `adjustSoftBlockageWeight` fires only at 1 -- so an untranslated
# threshold silently changes the soft-blockage WEIGHT, not just the clustering.
# ⚠️ The WEIGHT and utilization options too: an untranslated `-boundary_weight 0.0` leaves a term
# live that the case turned OFF, and `-target_util` ramps the utilization list from a different base.
NUMERIC = {
    "-boundary_weight": "--boundary-weight",
    "-notch_weight": "--notch-weight",
    "-guidance_weight": "--guidance-weight",
    "-target_util": "--target-util",
}
THRESH = {
    "-max_num_inst": "--max-num-inst",
    "-min_num_inst": "--min-num-inst",
    "-max_num_macro": "--max-num-macro",
    "-min_num_macro": "--min-num-macro",
}

KNOWN = ("set_macro_halo", "set_macro_base_halo", "-use_full_halo",
         "set_macro_guidance_region")

ROW = re.compile(r"^\s*(.+?)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*$")
TOTAL = re.compile(r"^\s*Total Cost\s+([\d.]+)\s*$")


def flags(case):
    path = os.path.join(tcl_dir, case + ".tcl")
    if not os.path.exists(path):
        return []
    text = io.open(path, encoding="utf-8").read()
    out = []
    for name, vals in MACRO_HALO.findall(text):
        out += ["--macro-halo", f"{name}={','.join(vals.split())}"]
    for vals in BASE_HALO.findall(text):
        out += ["--base-halo", ",".join(vals.split())]
    if "-use_full_halo" in text:
        out += ["--use-full-halo"]
    for name, vals in GUIDE.findall(text):
        out += ["--macro-guide", f"{name}={','.join(vals.split())}"]
    for tcl_opt, flag in THRESH.items():
        m = re.search(re.escape(tcl_opt) + r"\s+(\d+)", text)
        if m:
            out += [flag, m.group(1)]
    for tcl_opt, flag in NUMERIC.items():
        m = re.search(re.escape(tcl_opt) + r"\s+([0-9.]+)", text)
        if m:
            out += [flag, m.group(1)]
    return out


def tables(text, marker="Cluster Placement Summary"):
    """Every summary of one kind in a log, as [{rows: {term: (w, v, n, c)}, total: x}]."""
    out, cur = [], None
    for line in text.splitlines():
        if line.strip() == marker:
            cur = {"rows": {}, "total": None}
            out.append(cur)
            continue
        if cur is None:
            continue
        m = TOTAL.match(line)
        if m:
            cur["total"] = m.group(1)
            cur = None
            continue
        m = ROW.match(line)
        if m and m.group(1) not in ("Penalty Type",):
            cur["rows"][m.group(1)] = m.group(2, 3, 4, 5)
    return out


cases = sorted(f[:-4] for f in os.listdir(log_dir) if f.endswith(".log"))
# [differ, match] for the macro summaries.
macro_counts = [0, 0]
ok = differ = macro_path = refused = 0
bad_terms = {}
for case in cases:
    ref_text = io.open(
        os.path.join(log_dir, case + ".log"), encoding="utf-8", errors="replace"
    ).read()
    ref = tables(ref_text)
    if not ref:
        print(f"  {case:32} macro-path (no cluster summary)"); macro_path += 1; continue
    path = os.path.join(odb_dir, case + ".odb")
    if not os.path.exists(path):
        print(f"  {case:32} NO ODB"); refused += 1; continue
    r = subprocess.run(["./target/debug/cluster-dump", "--shaping", "--placement-trace"]
                       + flags(case) + [path], capture_output=True, text=True)
    got = tables(r.stdout)
    # 🔑 The MACRO summaries are scored too — `placeMacros` runs on nearly every design, several
    # times on some, and its table is the five-term one the hard core prints.
    want_macro = tables(ref_text, "Macro Placement Summary")
    got_macro = tables(r.stdout, "Macro Placement Summary")
    if want_macro:
        if len(got_macro) != len(want_macro):
            macro_counts[0] += 1
            print(f"  {case:32} MACRO {len(got_macro)} tables, upstream has {len(want_macro)}")
        elif got_macro == want_macro:
            macro_counts[1] += 1
        else:
            macro_counts[0] += 1
            for g, e in zip(got_macro, want_macro):
                for term, w in e["rows"].items():
                    if g["rows"].get(term) != w:
                        print(f"  {case:32} MACRO {term}: {g['rows'].get(term)} != {w}")
                        break
                else:
                    if g["total"] != e["total"]:
                        print(f"  {case:32} MACRO TOTAL: {g['total']} != {e['total']}")
                        break
                    continue
                break
    if len(got) != len(ref):
        print(f"  {case:32} {len(got)} tables, upstream has {len(ref)}"); differ += 1; continue
    diffs = []
    for i, (g, e) in enumerate(zip(got, ref)):
        for term, want in e["rows"].items():
            have = g["rows"].get(term)
            if have != want:
                diffs.append(f"{term}: {have} != {want}")
                bad_terms[term] = bad_terms.get(term, 0) + 1
        if g["total"] != e["total"]:
            diffs.append(f"TOTAL: {g['total']} != {e['total']}")
            bad_terms["TOTAL"] = bad_terms.get("TOTAL", 0) + 1
    if diffs:
        print(f"  {case:32} DIFFERS  {diffs[0]}" + (f"  (+{len(diffs)-1} more)" if len(diffs) > 1 else ""))
        differ += 1
    else:
        print(f"  {case:32} match ({len(got)} table(s))")
        ok += 1

print(f"\ncluster: {ok} match, {differ} differ, {macro_path} macro-path, {refused} refused, of {len(cases)}")
print(f"macro:   {macro_counts[1]} match, {macro_counts[0]} differ")
if bad_terms:
    print("terms differing, by count: " + ", ".join(
        f"{t}={n}" for t, n in sorted(bad_terms.items(), key=lambda kv: -kv[1])))
raise SystemExit(1 if differ or refused else 0)
